### ISSUE TITLE
Unknown variable meaning 

### ISSUE THREAD

**Issue by jmahabali** [sleepepi/chat-data-dictionary#305]
Figure out meaning of **slh3c_ck** variable

**Comment by mrueschman** [comment]
![image](https://cloud.githubusercontent.com/assets/707167/17304803/6a80d816-57f5-11e6-82b2-153eb7766847.png)

Variable is the "Not Sure" checkbox after 3c.

**Comment by mrueschman** [comment]
Closed in https://github.com/sleepepi/chat-data-dictionary/commit/60f7426c11d71db7458e696a445a114e23182528
