### ISSUE TITLE
Eliminate redundant CHAT variables

### ISSUE THREAD

**Issue by StephanieMarvin** [sleepepi/chat-data-dictionary#315]
@mrueschman The following variables for the CHAT data dictionary may need to be eliminated:

slp_time
slptimem
slp_lat
slplatm
time_bed
timebedm

**Comment by mrueschman** [comment]
Hi Mike.  Looks like these 2 fields in the CHAT data dictionary are the same?
 
osas18: OSA-18 Survey Score (sum of all 18 resp)
totalosa:              OSA-18 Survey Score (sum of all 18 resp)
 
Thanks,
Carole
